### ISSUE TITLE
version 3.2.0 crashes in windows 7 

### ISSUE THREAD

**Issue by pejman1** [Alex-D/check-disk-space#17] opened 2022-02-14 07:33 UTC
I am writing to inform you there is bug in version 3.2.0 that cause app crashes in windows 7

**Comment by Alex-D** [comment] 2022-03-06 13:24
The real question is: should we support Windows 7 as of 2022?
Microsoft themself has ended support for Windows 7 already two years ago: 
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

**Comment by pejman1** [comment] 2022-03-06 19:21
> The real question is: should we support Windows 7 as of 2022? Microsoft themself has ended support for Windows 7 already two years ago: https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
> 
> Also, without logs, I can't know the crash origin, so I can't fix it.

there are many users that still use windows 7

**Comment by Alex-D** [comment] 2022-03-06 21:43
The package code use this Powershell function here:
https://github.com/Alex-D/check-disk-space/blob/8d1889109fff96da4b276723f45c5757d447c424/src/index.ts#L105

that Microsoft documents as working since Windows Vista :/

I will download a Windows 7 VM to try to reproduce the crash

**Comment by Alex-D** [comment] 2022-03-07 01:11
I've installed a Windows 7 VM, and I can reproduce it since it seems to be due to PowerShell 2.

I've found some users complaining about that on the node repository:
https://github.com/nodejs/node/issues/25645#issuecomment-456778269

So, I need to found a workaround :/

**Comment by Alex-D** [comment] 2022-03-07 02:12
Fixed in 3.3.0
Now, I switch between the old and the new way depending on the Windows version used.
That way, I keep the support of older Windows that does not support PowerShell 3 which is needed for the `Get-CimInstance` cmdlet.

**Closed by Alex-D** 2022-03-07 02:12 UTC
